---
- id: explicit-imports
  name: ExplicitImports checks
  description: "ExplicitImports.jl namespace checks"
  language: julia
  entry: ./scripts/explicit-imports.jl --check
  types: [julia]
  minimum_pre_commit_version: "4.1.0"
